"""many-to-many add playlist table

Revision ID: 08f792d76fe6
Revises: f3e8955f6829
Create Date: 2024-02-19 17:22:52.521750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f792d76fe6'
down_revision: Union[str, None] = 'f3e8955f6829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Playlists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist_song',
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('playlist_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['Playlists.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['Songs.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_song')
    op.drop_table('Playlists')
    # ### end Alembic commands ###
